*** Starting uWSGI 2.0.19.1 (64bit) on [Fri Feb 26 11:19:22 2021] ***
compiled with version: 9.3.0 on 12 February 2021 13:45:27
os: Linux-5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020
nodename: 247d064baaf4
machine: x86_64
clock source: unix
detected number of CPU cores: 40
current working directory: /root/AI
detected binary path: /usr/local/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:5000 fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC 9.3.0]
Python main interpreter initialized at 0x55758ef361d0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 876672 bytes (856 KB) for 48 cores
*** Operational MODE: preforking+threaded ***
2021-02-26 11:19:22.956248: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-26 11:19:22.956319: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x55758ef361d0 pid: 41461 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (pid: 41461, cores: 8)
spawned uWSGI worker 2 (pid: 41541, cores: 8)
spawned uWSGI worker 3 (pid: 41549, cores: 8)
spawned uWSGI worker 4 (pid: 41557, cores: 8)
spawned uWSGI worker 5 (pid: 41565, cores: 8)
spawned uWSGI worker 6 (pid: 41573, cores: 8)
[pid: 41461|app: 0|req: 1/1] 172.17.0.1 () {46 vars in 824 bytes} [Fri Feb 26 11:19:34 2021] OPTIONS /detect_face/ => generated 0 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 0)
[pid: 41565|app: 0|req: 1/2] 172.17.0.1 () {50 vars in 881 bytes} [Fri Feb 26 11:19:35 2021] OPTIONS /detect_face/ => generated 0 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 0)
2021-02-26 11:19:35.287621: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-26 11:19:35.289584: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-02-26 11:19:35.336157: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-02-26 11:19:35.336217: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (247d064baaf4): /proc/driver/nvidia/version does not exist
2021-02-26 11:19:35.338512: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-26 11:19:35.702357: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-26 11:19:35.703945: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2799960000 Hz
{'success': 'False'}
[pid: 41573|app: 0|req: 2/3] 172.17.0.1 () {52 vars in 883 bytes} [Fri Feb 26 11:19:35 2021] POST /detect_face/ => generated 20 bytes in 1371 msecs (HTTP/1.1 200) 2 headers in 71 bytes (5 switches on core 2)
[pid: 41573|app: 0|req: 3/4] 172.17.0.1 () {46 vars in 824 bytes} [Fri Feb 26 11:19:41 2021] OPTIONS /detect_face/ => generated 0 bytes in 150 msecs (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 3)
{'success': 'True'}
[pid: 41573|app: 0|req: 4/5] 172.17.0.1 () {44 vars in 788 bytes} [Fri Feb 26 11:19:34 2021] POST /detect_face/ => generated 19 bytes in 7649 msecs (HTTP/1.1 200) 2 headers in 71 bytes (817 switches on core 0)
[pid: 41461|app: 0|req: 2/6] 172.17.0.1 () {46 vars in 824 bytes} [Fri Feb 26 11:19:48 2021] OPTIONS /detect_face/ => generated 0 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 2)
[uwsgi-body-read] Timeout reading 917395 bytes. Content-Length: 1484755 consumed: 567360 left: 917395
[pid: 41573|app: 0|req: 8/7] 172.17.0.1 () {44 vars in 788 bytes} [Fri Feb 26 11:19:49 2021] POST /detect_face/ => generated 192 bytes in 14693 msecs (HTTP/1.1 400) 2 headers in 89 bytes (325 switches on core 3)
[uwsgi-body-read] Timeout reading 724252 bytes. Content-Length: 1484572 consumed: 760320 left: 724252
[pid: 41573|app: 0|req: 8/8] 172.17.0.1 () {44 vars in 788 bytes} [Fri Feb 26 11:19:42 2021] POST /detect_face/ => generated 192 bytes in 21839 msecs (HTTP/1.1 400) 2 headers in 89 bytes (466 switches on core 6)
[uwsgi-body-read] Timeout reading 521931 bytes. Content-Length: 1488171 consumed: 966240 left: 521931
[pid: 41573|app: 0|req: 8/9] 172.17.0.1 () {44 vars in 788 bytes} [Fri Feb 26 11:19:41 2021] POST /detect_face/ => generated 192 bytes in 22472 msecs (HTTP/1.1 400) 2 headers in 89 bytes (592 switches on core 5)
[uwsgi-body-read] Timeout reading 674161 bytes. Content-Length: 1482001 consumed: 807840 left: 674161
[pid: 41573|app: 0|req: 8/10] 172.17.0.1 () {44 vars in 788 bytes} [Fri Feb 26 11:19:42 2021] POST /detect_face/ => generated 192 bytes in 21618 msecs (HTTP/1.1 400) 2 headers in 89 bytes (485 switches on core 7)
[uwsgi-body-read] Timeout reading 798392 bytes. Content-Length: 1482392 consumed: 684000 left: 798392
[pid: 41541|app: 0|req: 1/11] 172.17.0.1 () {44 vars in 788 bytes} [Fri Feb 26 11:19:43 2021] POST /detect_face/ => generated 192 bytes in 20629 msecs (HTTP/1.1 400) 2 headers in 89 bytes (421 switches on core 0)
[uwsgi-body-read] Timeout reading 992277 bytes. Content-Length: 1484757 consumed: 492480 left: 992277
[pid: 41573|app: 0|req: 8/12] 172.17.0.1 () {44 vars in 788 bytes} [Fri Feb 26 11:19:48 2021] POST /detect_face/ => generated 192 bytes in 15442 msecs (HTTP/1.1 400) 2 headers in 89 bytes (296 switches on core 1)
[pid: 41573|app: 0|req: 9/13] 172.17.0.1 () {50 vars in 881 bytes} [Fri Feb 26 11:20:16 2021] OPTIONS /detect_face/ => generated 0 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 0)
2021-02-26 11:20:16.395627: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-02-26 11:20:16.396864: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2021-02-26 11:20:16.445913: E tensorflow/stream_executor/cuda/cuda_driver.cc:328] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2021-02-26 11:20:16.445953: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (247d064baaf4): /proc/driver/nvidia/version does not exist
2021-02-26 11:20:16.448174: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
[pid: 41573|app: 0|req: 10/14] 172.17.0.1 () {50 vars in 999 bytes} [Fri Feb 26 11:20:16 2021] GET / => generated 232 bytes in 0 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 4)
2021-02-26 11:20:16.806028: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-02-26 11:20:16.807736: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2799960000 Hz
WARNING:tensorflow:5 out of the last 11 calls to <function Model.make_predict_function.<locals>.predict_function at 0x7ff74411e430> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
{'success': 'True'}
[pid: 41461|app: 0|req: 3/15] 172.17.0.1 () {52 vars in 884 bytes} [Fri Feb 26 11:20:16 2021] POST /detect_face/ => generated 19 bytes in 1578 msecs (HTTP/1.1 200) 2 headers in 71 bytes (9 switches on core 0)
[pid: 41573|app: 0|req: 11/16] 172.17.0.1 () {48 vars in 922 bytes} [Fri Feb 26 11:20:18 2021] GET /favicon.ico => generated 232 bytes in 1 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 2)
{'success': 'False'}
[pid: 41573|app: 0|req: 12/17] 172.17.0.1 () {52 vars in 884 bytes} [Fri Feb 26 11:20:20 2021] POST /detect_face/ => generated 20 bytes in 567 msecs (HTTP/1.1 200) 2 headers in 71 bytes (9 switches on core 3)
[pid: 41573|app: 0|req: 13/18] 172.17.0.1 () {50 vars in 1021 bytes} [Fri Feb 26 11:20:24 2021] GET /face_detect => generated 232 bytes in 1 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 6)
[pid: 41573|app: 0|req: 14/19] 172.17.0.1 () {50 vars in 881 bytes} [Fri Feb 26 11:20:26 2021] OPTIONS /detect_face/ => generated 0 bytes in 1 msecs (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 5)
{'success': 'False'}
[pid: 41573|app: 0|req: 15/20] 172.17.0.1 () {52 vars in 884 bytes} [Fri Feb 26 11:20:26 2021] POST /detect_face/ => generated 20 bytes in 564 msecs (HTTP/1.1 200) 2 headers in 71 bytes (10 switches on core 7)
[pid: 41573|app: 0|req: 16/21] 172.17.0.1 () {50 vars in 1021 bytes} [Fri Feb 26 11:20:30 2021] GET /detect_face => generated 295 bytes in 3 msecs (HTTP/1.1 308) 3 headers in 142 bytes (1 switches on core 1)
{'success': 'False'}
[pid: 41461|app: 0|req: 4/22] 172.17.0.1 () {52 vars in 884 bytes} [Fri Feb 26 11:20:30 2021] POST /detect_face/ => generated 20 bytes in 545 msecs (HTTP/1.1 200) 2 headers in 71 bytes (8 switches on core 4)
[2021-02-26 11:20:50,096] ERROR in app: Exception on /detect_face/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./app.py", line 39, in face_detect
    img=request.json['img']
TypeError: 'NoneType' object is not subscriptable
[pid: 41461|app: 0|req: 5/23] 172.17.0.1 () {38 vars in 797 bytes} [Fri Feb 26 11:20:50 2021] GET /detect_face/ => generated 290 bytes in 6 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 7)
[pid: 41565|app: 0|req: 2/24] 172.17.0.1 () {38 vars in 730 bytes} [Fri Feb 26 11:20:52 2021] GET /favicon.ico => generated 232 bytes in 2 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 2)
